GET https://google.com
###

POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=fceb1e53687448bbab8abb82fec80252&client_secret=973654b2da524add8b97c9d5ee4bd6bb
###

GET https://api.spotify.com/v1/search?q=promessa&type=artist
Authorization: Bearer BQB5sGe6YL90z2Vv0cTh2qR-Qw6RsJWYN33v9do3vm7yMAzvjEiUjr8Lb71tt2L7ncDahE80RQfjfZHKbHhtkla7okn7Nx8lP-wOMwt-Wxev1OkZMTKHlLRyKZNVMV_v4BIYS8YsoZg